version: '1'
services:
  web:
    build: .
    ports: 
     - "8080:8080"
    links:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "jacegonzales25"
    

